### ISSUE TITLE
sound effects

### ISSUE THREAD

**Issue by JdavisBro** [JdavisBro/DrawDogOnline#11]

**Comment by chevreaux** [comment]
An initial set of sound effects, based on the game files.

Movement:
- [x] jump
- - [x] jumping whoosh
- - [x] land
- [x] walk
- [x] stop
- [x] turnaround

(there are different sounds for each ground type, if we want to go that route)

Paint:
- [ ] stroke
- [ ] fill
- [ ] splat
- [ ] erase
- [ ] color change
- [ ] size change

Other stuff:
- [ ] emotes?
